version: 1.0.{build}
before_build:
- cmd: >-
    git submodule update --init --recursive

    nuget restore
build:
  verbosity: minimal
  project: StyleCop.Baboon.sln
test:
  assemblies: StyleCop.Baboon.Tests\bin\Debug\StyleCop.Baboon.Tests.dll

